# Generated by Django 4.1.3 on 2023-07-06 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condiciones',
            fields=[
                ('idCondiciones', models.AutoField(primary_key=True, serialize=False)),
                ('nCondiciones', models.IntegerField()),
                ('nombreCondicion', models.CharField(max_length=45)),
                ('descripcionCondicion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('idDispositivos', models.AutoField(primary_key=True, serialize=False)),
                ('IP', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45)),
                ('imgsPath', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Experimentos',
            fields=[
                ('idExperimentos', models.AutoField(primary_key=True, serialize=False)),
                ('nombreExperimento', models.CharField(max_length=90)),
                ('fechaInicio', models.DateTimeField()),
                ('ventanaEntreCapturas', models.IntegerField()),
                ('numeroDeCapturas', models.IntegerField()),
                ('aplicacion', models.CharField(max_length=90)),
                ('nombreProyecto', models.CharField(max_length=90)),
                ('tipoImgs', models.CharField(max_length=45)),
                ('resolucionImgs', models.CharField(max_length=45, null=True)),
                ('numeroImgs', models.IntegerField()),
                ('frecuencia', models.IntegerField()),
                ('color', models.CharField(default='#0646b4', max_length=45)),
                ('gusanosPorCondicion', models.IntegerField(null=True)),
                ('idUsuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Placas',
            fields=[
                ('idPlacas', models.AutoField(primary_key=True, serialize=False)),
                ('idPallets', models.IntegerField()),
                ('tipoPlaca', models.CharField(max_length=45)),
                ('cancelada', models.BooleanField(default=False)),
                ('posicion', models.CharField(max_length=45)),
                ('idCondiciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.condiciones')),
                ('idExperimentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experimentos')),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('idTareas', models.AutoField(primary_key=True, serialize=False)),
                ('fechayHora', models.DateTimeField()),
                ('holguraPositiva', models.IntegerField()),
                ('holguraNegativa', models.IntegerField()),
                ('parametrosProcesamiento', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('cancelada', models.BooleanField(default=False)),
                ('idDispositivos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dispositivos')),
                ('idExperimentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experimentos')),
                ('idUsuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resultados_lifespan',
            fields=[
                ('idResultados', models.AutoField(primary_key=True, serialize=False)),
                ('modo', models.CharField(max_length=45)),
                ('vivos', models.IntegerField(null=True)),
                ('muertos', models.IntegerField(null=True)),
                ('idPlacas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.placas')),
                ('idTareas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tareas')),
            ],
        ),
        migrations.CreateModel(
            name='Resultados_healthspan',
            fields=[
                ('idResultados', models.AutoField(primary_key=True, serialize=False)),
                ('modo', models.CharField(max_length=45)),
                ('idPlacas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.placas')),
                ('idTareas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tareas')),
            ],
        ),
        migrations.CreateModel(
            name='Pallets',
            fields=[
                ('idPallets', models.AutoField(primary_key=True, serialize=False)),
                ('localizacion', models.CharField(max_length=45)),
                ('idDispositivos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dispositivos')),
            ],
        ),
        migrations.AddField(
            model_name='condiciones',
            name='idExperimentos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experimentos'),
        ),
    ]
