# Generated by Django 4.1.3 on 2022-11-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ensayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(null=True)),
                ('inicio', models.TextField(null=True)),
                ('fin', models.TextField(null=True)),
                ('horas', models.TextField(null=True)),
            ],
        ),
    ]
