# Generated by Django 4.1.3 on 2023-02-28 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condiciones',
            fields=[
                ('idCondiciones', models.AutoField(primary_key=True, serialize=False)),
                ('nCondiciones', models.IntegerField()),
                ('descripcionCondicion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Experimentos',
            fields=[
                ('idExperimentos', models.AutoField(primary_key=True, serialize=False)),
                ('nombreExperimento', models.CharField(max_length=45)),
                ('fechaInicio', models.DateTimeField()),
                ('ventanaEntreCapturas', models.TimeField()),
                ('numeroDeCapturas', models.IntegerField()),
                ('aplicacion', models.CharField(max_length=45)),
                ('nombreProyecto', models.CharField(max_length=45)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Placas',
            fields=[
                ('idPlacas', models.AutoField(primary_key=True, serialize=False)),
                ('idRanura', models.IntegerField()),
                ('tipoPlaca', models.CharField(max_length=45)),
                ('idCondiciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.condiciones')),
                ('idExperimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experimentos')),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('idTareas', models.AutoField(primary_key=True, serialize=False)),
                ('fechayHora', models.DateTimeField()),
                ('rutaDeImagenes', models.CharField(max_length=90)),
                ('parametrosProcesamiento', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('idExperimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experimentos')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resultados_lifespan',
            fields=[
                ('idResultados', models.AutoField(primary_key=True, serialize=False)),
                ('modo', models.CharField(max_length=45)),
                ('vivos', models.IntegerField()),
                ('muertos', models.IntegerField()),
                ('idPlacas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.placas')),
                ('idTareas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tareas')),
            ],
        ),
    ]
