# Generated by Django 4.1.3 on 2023-03-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentos',
            name='ventanaEntreCapturas',
            field=models.IntegerField(),
        ),
    ]
