# Generated by Django 4.1.3 on 2023-06-26 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_experimentos_ventanaentrecapturas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('IP', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=45)),
                ('imgsPath', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='resultados_lifespan',
            name='muertos',
        ),
        migrations.RemoveField(
            model_name='resultados_lifespan',
            name='vivos',
        ),
        migrations.AddField(
            model_name='experimentos',
            name='color',
            field=models.CharField(default='#0646b4', max_length=45),
        ),
        migrations.AddField(
            model_name='experimentos',
            name='frecuencia',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentos',
            name='numeroImgs',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentos',
            name='resolucionImg',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='experimentos',
            name='tipoImgenes',
            field=models.CharField(default='rgb', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placas',
            name='posicion',
            field=models.CharField(default='0-0', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experimentos',
            name='aplicacion',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='experimentos',
            name='nombreExperimento',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='experimentos',
            name='nombreProyecto',
            field=models.CharField(max_length=90),
        ),
        migrations.CreateModel(
            name='Pallets',
            fields=[
                ('idPallets', models.AutoField(primary_key=True, serialize=False)),
                ('localizacion', models.CharField(max_length=45)),
                ('idDispositivos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dispositivos')),
            ],
        ),
    ]
