# Generated by Django 4.1.3 on 2023-06-26 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dispositivos_remove_resultados_lifespan_muertos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultados_lifespan',
            name='muertos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultados_lifespan',
            name='vivos',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Resultados_healthspan',
            fields=[
                ('idResultados', models.AutoField(primary_key=True, serialize=False)),
                ('modo', models.CharField(max_length=45)),
                ('idPlacas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.placas')),
                ('idTareas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tareas')),
            ],
        ),
    ]
