# Generated by Django 4.1.3 on 2023-07-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_resultados_lifespan_muertos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentos',
            old_name='resolucionImg',
            new_name='resolucionImgs',
        ),
        migrations.RenameField(
            model_name='experimentos',
            old_name='tipoImgenes',
            new_name='tipoImgs',
        ),
    ]
