# Generated by Django 4.1.3 on 2023-07-03 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_resolucionimg_experimentos_resolucionimgs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='rutaDeImagenes',
        ),
        migrations.AddField(
            model_name='tareas',
            name='holguraNegativa',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareas',
            name='holguraPositiva',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareas',
            name='idDispositivos',
            field=models.ForeignKey(default='localhost', on_delete=django.db.models.deletion.CASCADE, to='api.dispositivos'),
            preserve_default=False,
        ),
    ]
