# Generated by Django 4.1.3 on 2023-07-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_tareas_rutadeimagenes_tareas_holguranegativa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='idDispositivos',
        ),
    ]
